import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

@Injectable()
export class LoremIpsomService {
  public static Index = 0;
  private chunks: string[] = [];
  private len = 0;

  public Get(words: number): Observable<string[]> {
    if (!this.chunks || this.chunks && this.chunks.length === 0) {
      let data: string = Object.assign(loremIpsomData, '');
      data = data.replace(/[^A-Za-z0-9\s]/, '');
      this.chunks = data.split(/[\s]+/).slice(1, -1);
      this.len = this.chunks.length;
    }

    const index = LoremIpsomService.Index;
    const length = this.len;
    const chunks = Object.assign([], this.chunks);
    let ret = [];
    if (index + words > length) {
        ret = chunks.slice(index, -1);
        ret.concat(chunks.slice(0, index + words - length));
    } else {
        ret = chunks.slice(index, index + words);
    }

    LoremIpsomService.Index = (index + words) % length;
    return of(ret);
  }
}

const loremIpsomData = `
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam memini etiam quae nolo, oblivisci non possum quae volo. Atque haec ita iustitiae propria sunt, ut sint virtutum reliquarum communia. Sed quid minus probandum quam esse aliquem beatum nec satis beatum? Ita relinquet duas, de quibus etiam atque etiam consideret. Hoc tu nunc in illo probas.
            Sed haec in pueris; Nam Pyrrho, Aristo, Erillus iam diu abiecti. Bona autem corporis huic sunt, quod posterius posui, similiora. De vacuitate doloris eadem sententia erit. Ergo hoc quidem apparet, nos ad agendum esse natos. Tantum dico, magis fuisse vestrum agere Epicuri diem natalem, quam illius testamento cavere ut ageretur.
            Quamquam in hac divisione rem ipsam prorsus probo, elegantiam desidero. Isto modo, ne si avia quidem eius nata non esset. At quanta conantur! Mundum hunc omnem oppidum esse nostrum! Incendi igitur eos, qui audiunt, vides. Minime vero probatur huic disciplinae, de qua loquor, aut iustitiam aut amicitiam propter utilitates adscisci aut probari. Cupiditates non Epicuri divisione finiebat, sed sua satietate. Haec quo modo conveniant, non sane intellego. Dic in quovis conventu te omnia facere, ne doleas. De vacuitate doloris eadem sententia erit.
            Quarum ambarum rerum cum medicinam pollicetur, luxuriae licentiam pollicetur. Illud mihi a te nimium festinanter dictum videtur, sapientis omnis esse semper beatos; Nondum autem explanatum satis, erat, quid maxime natura vellet. Cur igitur, inquam, res tam dissimiles eodem nomine appellas?
            Quis suae urbis conservatorem Codrum, quis Erechthei filias non maxime laudat? Sed ego in hoc resisto; Videmus igitur ut conquiescere ne infantes quidem possint. Beatus autem esse in maximarum rerum timore nemo potest. An vero displicuit ea, quae tributa est animi virtutibus tanta praestantia? Res tota, Torquate, non doctorum hominum, velle post mortem epulis celebrari memoriam sui nominis.
            Qui autem esse poteris, nisi te amor ipse ceperit? Quare obscurentur etiam haec, quae secundum naturam esse dicimus, in vita beata; Quare, quoniam de primis naturae commodis satis dietum est nunc de maioribus consequentibusque videamus. Stuprata per vim Lucretia a regis filio testata civis se ipsa interemit. Ergo adhuc, quantum equidem intellego, causa non videtur fuisse mutandi nominis. Utilitatis causa amicitia est quaesita. Cuius similitudine perspecta in formarum specie ac dignitate transitum est ad honestatem dictorum atque factorum. Nihil acciderat ei, quod nollet, nisi quod anulum, quo delectabatur, in mari abiecerat. Stulti autem malorum memoria torquentur, sapientes bona praeterita grata recordatione renovata delectant. Traditur, inquit, ab Epicuro ratio neglegendi doloris.
            Tubulo putas dicere? Quid de Platone aut de Democrito loquar? Nos paucis ad haec additis finem faciamus aliquando; Sed in rebus apertissimis nimium longi sumus. Quid enim me prohiberet Epicureum esse, si probarem, quae ille diceret?
            Nihil opus est exemplis hoc facere longius. Iubet igitur nos Pythius Apollo noscere nosmet ipsos. Luxuriam non reprehendit, modo sit vacua infinita cupiditate et timore. Certe non potest. Egone non intellego, quid sit don Graece, Latine voluptas? Hoc etsi multimodis reprehendi potest, tamen accipio, quod dant. Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse; Hoc loco tenere se Triarius non potuit.
            Ita fit beatae vitae domina fortuna, quam Epicurus ait exiguam intervenire sapienti. Philosophi autem in suis lectulis plerumque moriuntur. Pauca mutat vel plura sane; Ita enim vivunt quidam, ut eorum vita refellatur oratio. Quid turpius quam sapientis vitam ex insipientium sermone pendere? Cupit enim dícere nihil posse ad beatam vitam deesse sapienti. Mihi enim satis est, ipsis non satis. Quacumque enim ingredimur, in aliqua historia vestigium ponimus. Inde sermone vario sex illa a Dipylo stadia confecimus. Quid dubitas igitur mutare principia naturae?
            Tum Piso: Quoniam igitur aliquid omnes, quid Lucius noster? Omnes enim iucundum motum, quo sensus hilaretur. Sit hoc ultimum bonorum, quod nunc a me defenditur; Quare hoc videndum est, possitne nobis hoc ratio philosophorum dare. Fortasse id optimum, sed ubi illud: Plus semper voluptatis? Sin kakan malitiam dixisses, ad aliud nos unum certum vitium consuetudo Latina traduceret. Sed audiamus ipsum: Compensabatur, inquit, tamen cum his omnibus animi laetitia, quam capiebam memoria rationum inventorumque nostrorum. Roges enim Aristonem, bonane ei videantur haec: vacuitas doloris, divitiae, valitudo; Quamquam id quidem, infinitum est in hac urbe; Cur post Tarentum ad Archytam?
            Non est ista, inquam, Piso, magna dissensio. Si mala non sunt, iacet omnis ratio Peripateticorum. Et hercule-fatendum est enim, quod sentio -mirabilis est apud illos contextus rerum. Utinam quidem dicerent alium alio beatiorem! Iam ruinas videres. An est aliquid, quod te sua sponte delectet? Et quidem, inquit, vehementer errat; Oculorum, inquit Plato, est in nobis sensus acerrimus, quibus sapientiam non cernimus. Quam nemo umquam voluptatem appellavit, appellat;
            Iubet igitur nos Pythius Apollo noscere nosmet ipsos. Expressa vero in iis aetatibus, quae iam confirmatae sunt. Quid, si etiam iucunda memoria est praeteritorum malorum? Erit enim instructus ad mortem contemnendam, ad exilium, ad ipsum etiam dolorem. Quis enim potest ea, quae probabilia videantur ei, non probare? Egone non intellego, quid sit don Graece, Latine voluptas? Ut optime, secundum naturam affectum esse possit.
            Quaesita enim virtus est, non quae relinqueret naturam, sed quae tueretur. Virtutis, magnitudinis animi, patientiae, fortitudinis fomentis dolor mitigari solet. Sed quid attinet de rebus tam apertis plura requirere? Haec mihi videtur delicatior, ut ita dicam, molliorque ratio, quam virtutis vis gravitasque postulat. Illis videtur, qui illud non dubitant bonum dicere -; Varietates autem iniurasque fortunae facile veteres philosophorum praeceptis instituta vita superabat. Sed quae tandem ista ratio est? Conferam tecum, quam cuique verso rem subicias; Conferam tecum, quam cuique verso rem subicias;
            Hanc quoque iucunditatem, si vis, transfer in animum; Quis Aristidem non mortuum diligit? Mene ergo et Triarium dignos existimas, apud quos turpiter loquare? Nam si propter voluptatem, quae est ista laus, quae possit e macello peti? Re mihi non aeque satisfacit, et quidem locis pluribus. Isto modo, ne si avia quidem eius nata non esset.
            Obsecro, inquit, Torquate, haec dicit Epicurus? Potius inflammat, ut coercendi magis quam dedocendi esse videantur. Nunc vero a primo quidem mirabiliter occulta natura est nec perspici nec cognosci potest. Duarum enim vitarum nobis erunt instituta capienda. Sed ita falsa sunt ea, quae consequuntur, ut illa, e quibus haec nata sunt, vera esse non possint. Qui non moveatur et offensione turpitudinis et comprobatione honestatis? Quodsi ipsam honestatem undique pertectam atque absolutam. Non est enim vitium in oratione solum, sed etiam in moribus.
            Suam denique cuique naturam esse ad vivendum ducem. Sed residamus, inquit, si placet. An eiusdem modi? Nemo nostrum istius generis asotos iucunde putat vivere. Quod idem cum vestri faciant, non satis magnam tribuunt inventoribus gratiam. Si id dicis, vicimus. Quis animo aequo videt eum, quem inpure ac flagitiose putet vivere?
            Portenta haec esse dicit, neque ea ratione ullo modo posse vivi; Stoici autem, quod finem bonorum in una virtute ponunt, similes sunt illorum; Res enim se praeclare habebat, et quidem in utraque parte. Conferam avum tuum Drusum cum C. Summum ením bonum exposuit vacuitatem doloris; Equidem e Cn. At miser, si in flagitiosa et vitiosa vita afflueret voluptatibus. Quae cum essent dicta, finem fecimus et ambulandi et disputandi. Quod idem cum vestri faciant, non satis magnam tribuunt inventoribus gratiam. Respondent extrema primis, media utrisque, omnia omnibus.
            At ille non pertimuit saneque fidenter: Istis quidem ipsis verbis, inquit; Illi enim inter se dissentiunt. Nunc dicam de voluptate, nihil scilicet novi, ea tamen, quae te ipsum probaturum esse confidam. Quod dicit Epicurus etiam de voluptate, quae minime sint voluptates, eas obscurari saepe et obrui. Quis enim potest ea, quae probabilia videantur ei, non probare? Atque ab isto capite fluere necesse est omnem rationem bonorum et malorum.
            Te ipsum, dignissimum maioribus tuis, voluptasne induxit, ut adolescentulus eriperes P. Quod cum accidisset ut alter alterum necopinato videremus, surrexit statim.
            Quo modo? Quid enim est a Chrysippo praetermissum in Stoicis? Etenim nec iustitia nec amicitia esse omnino poterunt, nisi ipsae per se expetuntur. Ut enim consuetudo loquitur, id solum dicitur honestum, quod est populari fama gloriosum. Sin dicit obscurari quaedam nec apparere, quia valde parva sint, nos quoque concedimus; Atqui pugnantibus et contrariis studiis consiliisque semper utens nihil quieti videre, nihil tranquilli potest. Sed residamus, inquit, si placet. Idque testamento cavebit is, qui nobis quasi oraculum ediderit nihil post mortem ad nos pertinere?
            Est enim tanti philosophi tamque nobilis audacter sua decreta defendere. Itaque a sapientia praecipitur se ipsam, si usus sit, sapiens ut relinquat. Verum esto: verbum ipsum voluptatis non habet dignitatem, nec nos fortasse intellegimus. Ut pulsi recurrant? Ego quoque, inquit, didicerim libentius si quid attuleris, quam te reprehenderim. Cur fortior sit, si illud, quod tute concedis, asperum et vix ferendum putabit? Qui non moveatur et offensione turpitudinis et comprobatione honestatis? Habes, inquam, Cato, formam eorum, de quibus loquor, philosophorum.
            Saepe ab Aristotele, a Theophrasto mirabiliter est laudata per se ipsa rerum scientia; Deinde disputat, quod cuiusque generis animantium statui deceat extremum. Quae sunt igitur communia vobis cum antiquis, iis sic utamur quasi concessis; Primum in nostrane potestate est, quid meminerimus? Itaque primos congressus copulationesque et consuetudinum instituendarum voluntates fieri propter voluptatem; Zenonis est, inquam, hoc Stoici. Iam contemni non poteris. Expectoque quid ad id, quod quaerebam, respondeas. Hoc ne statuam quidem dicturam pater aiebat, si loqui posset.
            Sit enim idem caecus, debilis. Teneo, inquit, finem illi videri nihil dolere. Licet hic rursus ea commemores, quae optimis verbis ab Epicuro de laude amicitiae dicta sunt. Octavio fuit, cum illam severitatem in eo filio adhibuit, quem in adoptionem D. Quid, si etiam iucunda memoria est praeteritorum malorum? Pisone in eo gymnasio, quod Ptolomaeum vocatur, unaque nobiscum Q.
            Legimus tamen Diogenem, Antipatrum, Mnesarchum, Panaetium, multos alios in primisque familiarem nostrum Posidonium. Iam contemni non poteris. Quid loquor de nobis, qui ad laudem et ad decus nati, suscepti, instituti sumus? Si quicquam extra virtutem habeatur in bonis. Quae diligentissime contra Aristonem dicuntur a Chryippo. Quantum Aristoxeni ingenium consumptum videmus in musicis? Beatus autem esse in maximarum rerum timore nemo potest. Contemnit enim disserendi elegantiam, confuse loquitur.
            Atque haec coniunctio confusioque virtutum tamen a philosophis ratione quadam distinguitur. Quorum altera prosunt, nocent altera. Fieri, inquam, Triari, nullo pacto potest, ut non dicas, quid non probes eius, a quo dissentias. Quamvis enim depravatae non sint, pravae tamen esse possunt. Isto modo ne improbos quidem, si essent boni viri. Illa sunt similia: hebes acies est cuipiam oculorum, corpore alius senescit; Studet enim meus is audire Cicero quaenam sit istius veteris, quam commemoras, Academiae de finibus bonorum Peripateticorumque sententia. Nos vero, inquit ille;
            Si quicquam extra virtutem habeatur in bonis. Etsi ea quidem, quae adhuc dixisti, quamvis ad aetatem recte isto modo dicerentur. Nec vero hoc oratione solum, sed multo magis vita et factis et moribus comprobavit. Proclivi currit oratio.
            At ille non pertimuit saneque fidenter: Istis quidem ipsis verbis, inquit; Itaque rursus eadem ratione, qua sum paulo ante usus, haerebitis. Quae similitudo in genere etiam humano apparet. Duarum enim vitarum nobis erunt instituta capienda. Ita multa dicunt, quae vix intellegam. Cur iustitia laudatur? Eam si varietatem diceres, intellegerem, ut etiam non dicente te intellego; Itaque homo in primis ingenuus et gravis, dignus illa familiaritate Scipionis et Laelii, Panaetius, cum ad Q. Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Hoc loco tenere se Triarius non potuit.
            Scio enim esse quosdam, qui quavis lingua philosophari possint; Laelius clamores sofòw ille so lebat Edere compellans gumias ex ordine nostros. Themistocles quidem, cum ei Simonides an quis alius artem memoriae polliceretur, Oblivionis, inquit, mallem. Primum in nostrane potestate est, quid meminerimus?
            Est igitur officium eius generis, quod nec in bonis ponatur nec in contrariis. Scio enim esse quosdam, qui quavis lingua philosophari possint; Quid autem habent admirationis, cum prope accesseris? Ita cum ea volunt retinere, quae superiori sententiae conveniunt, in Aristonem incidunt; Cum autem in quo sapienter dicimus, id a primo rectissime dicitur. Vitae autem degendae ratio maxime quidem illis placuit quieta. Cupiditates non Epicuri divisione finiebat, sed sua satietate.
            Tollenda est atque extrahenda radicitus. Atqui, inquit, si Stoicis concedis ut virtus sola, si adsit vitam efficiat beatam, concedis etiam Peripateticis. Contemnit enim disserendi elegantiam, confuse loquitur. Quid est, quod ab ea absolvi et perfici debeat? Verba tu fingas et ea dicas, quae non sentias? Quid ad utilitatem tantae pecuniae? Cum audissem Antiochum, Brute, ut solebam, cum M. Nosti, credo, illud: Nemo pius est, qui pietatem-; Quid, quod homines infima fortuna, nulla spe rerum gerendarum, opifices denique delectantur historia?
            Expectoque quid ad id, quod quaerebam, respondeas. Sed haec ab Antiocho, familiari nostro, dicuntur multo melius et fortius, quam a Stasea dicebantur. Sint ista Graecorum; Cur fortior sit, si illud, quod tute concedis, asperum et vix ferendum putabit?
            Sed ne, dum huic obsequor, vobis molestus sim. Iam illud quale tandem est, bona praeterita non effluere sapienti, mala meminisse non oportere? Quid de Platone aut de Democrito loquar?
            Non est ista, inquam, Piso, magna dissensio. Animum autem reliquis rebus ita perfecit, ut corpus; Verba tu fingas et ea dicas, quae non sentias? Hoc Hieronymus summum bonum esse dixit. Praeclare enim Plato: Beatum, cui etiam in senectute contigerit, ut sapientiam verasque opiniones assequi possit. Apud imperitos tum illa dicta sunt, aliquid etiam coronae datum;
            Nam de isto magna dissensio est. Paulum, cum regem Persem captum adduceret, eodem flumine invectio? Quorum sine causa fieri nihil putandum est. Quae qui non vident, nihil umquam magnum ac cognitione dignum amaverunt.
            Omnes enim iucundum motum, quo sensus hilaretur. Ut necesse sit omnium rerum, quae natura vigeant, similem esse finem, non eundem. Iam in altera philosophiae parte. Nam de summo mox, ut dixi, videbimus et ad id explicandum disputationem omnem conferemus. Re mihi non aeque satisfacit, et quidem locis pluribus. Eiuro, inquit adridens, iniquum, hac quidem de re; A quibus propter discendi cupiditatem videmus ultimas terras esse peragratas. Idemne potest esse dies saepius, qui semel fuit? Item de contrariis, a quibus ad genera formasque generum venerunt.
            Sed haec quidem liberius ab eo dicuntur et saepius. Ipse Epicurus fortasse redderet, ut Sextus Peducaeus, Sex. Eorum enim est haec querela, qui sibi cari sunt seseque diligunt. Tu autem, si tibi illa probabantur, cur non propriis verbis ea tenebas? Itaque eos id agere, ut a se dolores, morbos, debilitates repellant. Quae cum essent dicta, discessimus. Isto modo, ne si avia quidem eius nata non esset.
            In his igitur partibus duabus nihil erat, quod Zeno commutare gestiret. Non autem hoc: igitur ne illud quidem. Sed haec quidem liberius ab eo dicuntur et saepius. Oratio me istius philosophi non offendit; Iam quae corporis sunt, ea nec auctoritatem cum animi partibus, comparandam et cognitionem habent faciliorem. Sed eum qui audiebant, quoad poterant, defendebant sententiam suam. An hoc usque quaque, aliter in vita? Si qua in iis corrigere voluit, deteriora fecit.
            Familiares nostros, credo, Sironem dicis et Philodemum, cum optimos viros, tum homines doctissimos. Summum ením bonum exposuit vacuitatem doloris; Ergo adhuc, quantum equidem intellego, causa non videtur fuisse mutandi nominis. Quid ait Aristoteles reliquique Platonis alumni? Deinde disputat, quod cuiusque generis animantium statui deceat extremum. Ne amores quidem sanctos a sapiente alienos esse arbitrantur. Tum ille timide vel potius verecunde: Facio, inquit. Legimus tamen Diogenem, Antipatrum, Mnesarchum, Panaetium, multos alios in primisque familiarem nostrum Posidonium.
            Si est nihil nisi corpus, summa erunt illa: valitudo, vacuitas doloris, pulchritudo, cetera. Nemo igitur esse beatus potest. Indicant pueri, in quibus ut in speculis natura cernitur. Frater et T. Cur ipse Pythagoras et Aegyptum lustravit et Persarum magos adiit? Nos quidem Virtutes sic natae sumus, ut tibi serviremus, aliud negotii nihil habemus.
            Si stante, hoc natura videlicet vult, salvam esse se, quod concedimus; Sed potestne rerum maior esse dissensio? Quem Tiberina descensio festo illo die tanto gaudio affecit, quanto L. Sed quid attinet de rebus tam apertis plura requirere? Graecum enim hunc versum nostis omnes-: Suavis laborum est praeteritorum memoria. Ut pulsi recurrant? Omnes enim iucundum motum, quo sensus hilaretur. Igitur ne dolorem quidem. Quid ergo attinet gloriose loqui, nisi constanter loquare? Non igitur de improbo, sed de callido improbo quaerimus, qualis Q. Ergo ita: non posse honeste vivi, nisi honeste vivatur?
            In quibus doctissimi illi veteres inesse quiddam caeleste et divinum putaverunt. Quoniam, si dis placet, ab Epicuro loqui discimus. Stoicos roga. Qui potest igitur habitare in beata vita summi mali metus? Morbo gravissimo affectus, exul, orbus, egens, torqueatur eculeo: quem hunc appellas, Zeno? Mene ergo et Triarium dignos existimas, apud quos turpiter loquare? Illud quaero, quid ei, qui in voluptate summum bonum ponat, consentaneum sit dicere. Quo plebiscito decreta a senatu est consuli quaestio Cn.
            Oculorum, inquit Plato, est in nobis sensus acerrimus, quibus sapientiam non cernimus. Restatis igitur vos; Quid enim ab antiquis ex eo genere, quod ad disserendum valet, praetermissum est?
            Quae duo sunt, unum facit. Dat enim intervalla et relaxat. Vitae autem degendae ratio maxime quidem illis placuit quieta. Nobis aliter videtur, recte secusne, postea; At quicum ioca seria, ut dicitur, quicum arcana, quicum occulta omnia? Quod iam a me expectare noli. Hanc quoque iucunditatem, si vis, transfer in animum; Quod quidem iam fit etiam in Academia.
            Prave, nequiter, turpiter cenabat; Quod si ita se habeat, non possit beatam praestare vitam sapientia. Plane idem, inquit, et maxima quidem, qua fieri nulla maior potest. Perturbationes autem nulla naturae vi commoventur, omniaque ea sunt opiniones ac iudicia levitatis. Re mihi non aeque satisfacit, et quidem locis pluribus. Memini vero, inquam;
            Ut proverbia non nulla veriora sint quam vestra dogmata. Iam id ipsum absurdum, maximum malum neglegi. Quis enim potest ea, quae probabilia videantur ei, non probare? Ex quo illud efficitur, qui bene cenent omnis libenter cenare, qui libenter, non continuo bene. Non est igitur voluptas bonum. Morbo gravissimo affectus, exul, orbus, egens, torqueatur eculeo: quem hunc appellas, Zeno?
            Hic nihil fuit, quod quaereremus. Facit enim ille duo seiuncta ultima bonorum, quae ut essent vera, coniungi debuerunt; Sin laboramus, quis est, qui alienae modum statuat industriae? In quo etsi est magnus, tamen nova pleraque et perpauca de moribus. Stulti autem malorum memoria torquentur, sapientes bona praeterita grata recordatione renovata delectant.
            Apparet statim, quae sint officia, quae actiones. Quem Tiberina descensio festo illo die tanto gaudio affecit, quanto L. Apud ceteros autem philosophos, qui quaesivit aliquid, tacet; Ab his oratores, ab his imperatores ac rerum publicarum principes extiterunt.
            Quam tu ponis in verbis, ego positam in re putabam. Progredientibus autem aetatibus sensim tardeve potius quasi nosmet ipsos cognoscimus. Ut aliquid scire se gaudeant? Solum praeterea formosum, solum liberum, solum civem, stultost; An tu me de L. Si verbum sequimur, primum longius verbum praepositum quam bonum. Dic in quovis conventu te omnia facere, ne doleas.
            Nunc omni virtuti vitium contrario nomine opponitur. Inde sermone vario sex illa a Dipylo stadia confecimus. Perturbationes autem nulla naturae vi commoventur, omniaque ea sunt opiniones ac iudicia levitatis. Eadem fortitudinis ratio reperietur. Aliter homines, aliter philosophos loqui putas oportere? Si enim ita est, vide ne facinus facias, cum mori suadeas. Hoc mihi cum tuo fratre convenit. Quis enim confidit semper sibi illud stabile et firmum permansurum, quod fragile et caducum sit?
            Nam Metrodorum non puto ipsum professum, sed, cum appellaretur ab Epicuro, repudiare tantum beneficium noluisse; Cuius ad naturam apta ratio vera illa et summa lex a philosophis dicitur. Duo enim genera quae erant, fecit tria. Virtutis, magnitudinis animi, patientiae, fortitudinis fomentis dolor mitigari solet. Sed ad bona praeterita redeamus. Conferam tecum, quam cuique verso rem subicias; Quis Pullum Numitorium Fregellanum, proditorem, quamquam rei publicae nostrae profuit, non odit? At iste non dolendi status non vocatur voluptas.
            At quicum ioca seria, ut dicitur, quicum arcana, quicum occulta omnia? Quo modo autem optimum, si bonum praeterea nullum est? Certe nihil nisi quod possit ipsum propter se iure laudari. Nam Pyrrho, Aristo, Erillus iam diu abiecti. Itaque haec cum illis est dissensio, cum Peripateticis nulla sane. Ita ne hoc quidem modo paria peccata sunt. Quamquam tu hanc copiosiorem etiam soles dicere.
            Eam si varietatem diceres, intellegerem, ut etiam non dicente te intellego; Quamvis enim depravatae non sint, pravae tamen esse possunt. Hoc est non modo cor non habere, sed ne palatum quidem. Diodorus, eius auditor, adiungit ad honestatem vacuitatem doloris.
            In his igitur partibus duabus nihil erat, quod Zeno commutare gestiret. Si verbum sequimur, primum longius verbum praepositum quam bonum. Deinde disputat, quod cuiusque generis animantium statui deceat extremum. Quod autem principium officii quaerunt, melius quam Pyrrho;
            In quo etsi est magnus, tamen nova pleraque et perpauca de moribus. Summus dolor plures dies manere non potest? Quem si tenueris, non modo meum Ciceronem, sed etiam me ipsum abducas licebit. Quid igitur, inquit, eos responsuros putas? Quae cum ita sint, effectum est nihil esse malum, quod turpe non sit. Inscite autem medicinae et gubernationis ultimum cum ultimo sapientiae comparatur. Intellegi quidem, ut propter aliam quampiam rem, verbi gratia propter voluptatem, nos amemus; Atqui eorum nihil est eius generis, ut sit in fine atque extrerno bonorum. Ita graviter et severe voluptatem secrevit a bono. Ut nemo dubitet, eorum omnia officia quo spectare, quid sequi, quid fugere debeant? Quid ergo aliud intellegetur nisi uti ne quae pars naturae neglegatur? Alterum significari idem, ut si diceretur, officia media omnia aut pleraque servantem vivere.
            Quid enim ab antiquis ex eo genere, quod ad disserendum valet, praetermissum est? Minime vero istorum quidem, inquit. Ad quorum et cognitionem et usum iam corroborati natura ipsa praeeunte deducimur. Vide, quantum, inquam, fallare, Torquate. Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Graecum enim hunc versum nostis omnes-: Suavis laborum est praeteritorum memoria. Quae enim adhuc protulisti, popularia sunt, ego autem a te elegantiora desidero. Itaque nostrum est-quod nostrum dico, artis est-ad ea principia, quae accepimus.
            Atque his de rebus et splendida est eorum et illustris oratio. Quis negat? Quis negat? A mene tu?
            Mihi, inquam, qui te id ipsum rogavi? Itaque eos id agere, ut a se dolores, morbos, debilitates repellant. Quae hic rei publicae vulnera inponebat, eadem ille sanabat. Maximus dolor, inquit, brevis est. Facillimum id quidem est, inquam. Sed id ne cogitari quidem potest quale sit, ut non repugnet ipsum sibi. Recte, inquit, intellegis. Itaque e contrario moderati aequabilesque habitus, affectiones ususque corporis apti esse ad naturam videntur. Contineo me ab exemplis. Totum autem id externum est, et quod externum, id in casu est. At enim hic etiam dolore. Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret.
            Intellegi quidem, ut propter aliam quampiam rem, verbi gratia propter voluptatem, nos amemus; Haec para/doca illi, nos admirabilia dicamus. Itaque ad tempus ad Pisonem omnes. Ita enim vivunt quidam, ut eorum vita refellatur oratio.
            Scio enim esse quosdam, qui quavis lingua philosophari possint; In qua quid est boni praeter summam voluptatem, et eam sempiternam? Non igitur de improbo, sed de callido improbo quaerimus, qualis Q. Tecum optime, deinde etiam cum mediocri amico. Oratio me istius philosophi non offendit; Hoc enim constituto in philosophia constituta sunt omnia.
            Quamvis enim depravatae non sint, pravae tamen esse possunt. Idem iste, inquam, de voluptate quid sentit? Faceres tu quidem, Torquate, haec omnia; Quae iam oratio non a philosopho aliquo, sed a censore opprimenda est. Istam voluptatem perpetuam quis potest praestare sapienti? Nam nec vir bonus ac iustus haberi debet qui, ne malum habeat, abstinet se ab iniuria. Sed quot homines, tot sententiae;
            Non enim, si omnia non sequebatur, idcirco non erat ortus illinc. Quid ergo hoc loco intellegit honestum? Ita enim vivunt quidam, ut eorum vita refellatur oratio. Negabat igitur ullam esse artem, quae ipsa a se proficisceretur; Deinde dolorem quem maximum? Eorum enim omnium multa praetermittentium, dum eligant aliquid, quod sequantur, quasi curta sententia; An quod ita callida est, ut optime possit architectari voluptates? Sed nimis multa. Hoc etsi multimodis reprehendi potest, tamen accipio, quod dant. Ille vero, si insipiens-quo certe, quoniam tyrannus -, numquam beatus; Non enim, si omnia non sequebatur, idcirco non erat ortus illinc.
            Inde sermone vario sex illa a Dipylo stadia confecimus. Nunc omni virtuti vitium contrario nomine opponitur. Ne discipulum abducam, times. Huius, Lyco, oratione locuples, rebus ipsis ielunior. Aliter enim nosmet ipsos nosse non possumus. Re mihi non aeque satisfacit, et quidem locis pluribus. Sed nimis multa. Quamquam haec quidem praeposita recte et reiecta dicere licebit. Quid, quod res alia tota est? Tantum dico, magis fuisse vestrum agere Epicuri diem natalem, quam illius testamento cavere ut ageretur. Omnes enim iucundum motum, quo sensus hilaretur.
            Quis non odit sordidos, vanos, leves, futtiles? At hoc in eo M. Sed ille, ut dixi, vitiose. Quid est enim aliud esse versutum? Quis non odit sordidos, vanos, leves, futtiles? Quae cum magnifice primo dici viderentur, considerata minus probabantur. -, sed ut hoc iudicaremus, non esse in iis partem maximam positam beate aut secus vivendi. Vitae autem degendae ratio maxime quidem illis placuit quieta.
            Eiuro, inquit adridens, iniquum, hac quidem de re; Primum in nostrane potestate est, quid meminerimus? Quo modo autem optimum, si bonum praeterea nullum est? Tum ille timide vel potius verecunde: Facio, inquit. Quem ad modum quis ambulet, sedeat, qui ductus oris, qui vultus in quoque sit? Stulti autem malorum memoria torquentur, sapientes bona praeterita grata recordatione renovata delectant. Cur deinde Metrodori liberos commendas? Negat enim summo bono afferre incrementum diem.
            Nam Pyrrho, Aristo, Erillus iam diu abiecti. Tum Piso: Quoniam igitur aliquid omnes, quid Lucius noster? Sed utrum hortandus es nobis, Luci, inquit, an etiam tua sponte propensus es? Qui non moveatur et offensione turpitudinis et comprobatione honestatis? Tu vero, inquam, ducas licet, si sequetur; At vero illa, quae Peripatetici, quae Stoici dicunt, semper tibi in ore sunt in iudiciis, in senatu.
            Sed quia studebat laudi et dignitati, multum in virtute processerat. Non semper, inquam; Quod idem cum vestri faciant, non satis magnam tribuunt inventoribus gratiam. Totum autem id externum est, et quod externum, id in casu est. Voluptatem cum summum bonum diceret, primum in eo ipso parum vidit, deinde hoc quoque alienum; Vide igitur ne non debeas verbis nostris uti, sententiis tuis.
            Quid autem habent admirationis, cum prope accesseris? Zenonis est, inquam, hoc Stoici. Hoc etsi multimodis reprehendi potest, tamen accipio, quod dant. Cum id quoque, ut cupiebat, audivisset, evelli iussit eam, qua erat transfixus, hastam. Sed nonne merninisti licere mihi ista probare, quae sunt a te dicta? Itaque rursus eadem ratione, qua sum paulo ante usus, haerebitis.
            Mihi enim satis est, ipsis non satis. At ego quem huic anteponam non audeo dicere; Obsecro, inquit, Torquate, haec dicit Epicurus? Quae si potest singula consolando levare, universa quo modo sustinebit?
            Mihi enim satis est, ipsis non satis. Venit enim mihi Platonis in mentem, quem accepimus primum hic disputare solitum; Tecum optime, deinde etiam cum mediocri amico. Venit enim mihi Platonis in mentem, quem accepimus primum hic disputare solitum; Nihil minus, contraque illa hereditate dives ob eamque rem laetus. Ut optime, secundum naturam affectum esse possit. Quasi ego id curem, quid ille aiat aut neget. Esse enim quam vellet iniquus iustus poterat inpune. Equidem e Cn. Verba tu fingas et ea dicas, quae non sentias?
            Obsecro, inquit, Torquate, haec dicit Epicurus? Nam, ut paulo ante docui, augendae voluptatis finis est doloris omnis amotio. Istam voluptatem, inquit, Epicurus ignorat? Primum in nostrane potestate est, quid meminerimus? Indicant pueri, in quibus ut in speculis natura cernitur. Sumenda potius quam expetenda.
            Deinde dolorem quem maximum? Facillimum id quidem est, inquam. Quicquid enim a sapientia proficiscitur, id continuo debet expletum esse omnibus suis partibus; Ita enim vivunt quidam, ut eorum vita refellatur oratio. Ut proverbia non nulla veriora sint quam vestra dogmata. Igitur neque stultorum quisquam beatus neque sapientium non beatus. Hoc positum in Phaedro a Platone probavit Epicurus sensitque in omni disputatione id fieri oportere. Ergo id est convenienter naturae vivere, a natura discedere. Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret.
            Ergo omni animali illud, quod appetiti positum est in eo, quod naturae est accommodatum. Itaque eos id agere, ut a se dolores, morbos, debilitates repellant. Quod ea non occurrentia fingunt, vincunt Aristonem;
            Sit sane ista voluptas. Quod ea non occurrentia fingunt, vincunt Aristonem; Quaesita enim virtus est, non quae relinqueret naturam, sed quae tueretur. An vero displicuit ea, quae tributa est animi virtutibus tanta praestantia? Ut placet, inquit, etsi enim illud erat aptius, aequum cuique concedere. Consequens enim est et post oritur, ut dixi. Quid est igitur, cur ita semper deum appellet Epicurus beatum et aeternum? Si sapiens, ne tum quidem miser, cum ab Oroete, praetore Darei, in crucem actus est. Quae animi affectio suum cuique tribuens atque hanc, quam dico. Idem etiam dolorem saepe perpetiuntur, ne, si id non faciant, incidant in maiorem. Quid enim de amicitia statueris utilitatis causa expetenda vides.
            An eum discere ea mavis, quae cum plane perdidiceriti nihil sciat? Quae cum ita sint, effectum est nihil esse malum, quod turpe non sit. Si alia sentit, inquam, alia loquitur, numquam intellegam quid sentiat; Tu enim ista lenius, hic Stoicorum more nos vexat. Non enim, si omnia non sequebatur, idcirco non erat ortus illinc. Itaque vides, quo modo loquantur, nova verba fingunt, deserunt usitata.
            Quod cum ille dixisset et satis disputatum videretur, in oppidum ad Pomponium perreximus omnes. Negat enim summo bono afferre incrementum diem. A villa enim, credo, et: Si ibi te esse scissem, ad te ipse venissem. Nullus est igitur cuiusquam dies natalis. Magno hic ingenio, sed res se tamen sic habet, ut nimis imperiosi philosophi sit vetare meminisse. Dulce amarum, leve asperum, prope longe, stare movere, quadratum rotundum. Bonum patria: miserum exilium. Verum hoc idem saepe faciamus.
            Duo enim genera quae erant, fecit tria. Quod ea non occurrentia fingunt, vincunt Aristonem; Non enim, si omnia non sequebatur, idcirco non erat ortus illinc. Hoc tu nunc in illo probas.
            Nam et a te perfici istam disputationem volo, nec tua mihi oratio longa videri potest. Huic mori optimum esse propter desperationem sapientiae, illi propter spem vivere. Itaque his sapiens semper vacabit. Fortitudinis quaedam praecepta sunt ac paene leges, quae effeminari virum vetant in dolore. Cum id quoque, ut cupiebat, audivisset, evelli iussit eam, qua erat transfixus, hastam. An vero, inquit, quisquam potest probare, quod perceptfum, quod. Proclivi currit oratio.
            Ergo in gubernando nihil, in officio plurimum interest, quo in genere peccetur. At eum nihili facit; Sed venio ad inconstantiae crimen, ne saepius dicas me aberrare; Quid enim me prohiberet Epicureum esse, si probarem, quae ille diceret? Eodem modo is enim tibi nemo dabit, quod, expetendum sit, id esse laudabile. Cur post Tarentum ad Archytam? Estne, quaeso, inquam, sitienti in bibendo voluptas? Sed utrum hortandus es nobis, Luci, inquit, an etiam tua sponte propensus es?
            Atque haec ita iustitiae propria sunt, ut sint virtutum reliquarum communia. Quid, quod homines infima fortuna, nulla spe rerum gerendarum, opifices denique delectantur historia? Quae duo sunt, unum facit. Hoc uno captus Erillus scientiam summum bonum esse defendit nec rem ullam aliam per se expetendam. Quid censes in Latino fore? Reguli reiciendam; Cur id non ita fit? Quamquam in hac divisione rem ipsam prorsus probo, elegantiam desidero.
            Et quod est munus, quod opus sapientiae? Commoda autem et incommoda in eo genere sunt, quae praeposita et reiecta diximus; Honesta oratio, Socratica, Platonis etiam. Ut scias me intellegere, primum idem esse dico voluptatem, quod ille don. Nam de isto magna dissensio est. Cave putes quicquam esse verius. Sin aliud quid voles, postea.
            Scientiam pollicentur, quam non erat mirum sapientiae cupido patria esse cariorem. Aut unde est hoc contritum vetustate proverbium: quicum in tenebris? Videamus animi partes, quarum est conspectus illustrior; Mihi quidem Antiochum, quem audis, satis belle videris attendere.
            Hinc ceteri particulas arripere conati suam quisque videro voluit afferre sententiam. Quid, quod res alia tota est? Quae hic rei publicae vulnera inponebat, eadem ille sanabat. Ne vitationem quidem doloris ipsam per se quisquam in rebus expetendis putavit, nisi etiam evitare posset. Cur iustitia laudatur? Non pugnem cum homine, cur tantum habeat in natura boni; Ergo hoc quidem apparet, nos ad agendum esse natos. Ad corpus diceres pertinere-, sed ea, quae dixi, ad corpusne refers? Proclivi currit oratio.
            Multa sunt dicta ab antiquis de contemnendis ac despiciendis rebus humanis; Nam et complectitur verbis, quod vult, et dicit plane, quod intellegam; Quamquam haec quidem praeposita recte et reiecta dicere licebit.
            Id mihi magnum videtur. Aliter homines, aliter philosophos loqui putas oportere? Qui bonum omne in virtute ponit, is potest dicere perfici beatam vitam perfectione virtutis; Laboro autem non sine causa; Quamquam tu hanc copiosiorem etiam soles dicere. Illud dico, ea, quae dicat, praeclare inter se cohaerere.
            Uterque enim summo bono fruitur, id est voluptate. Satis est tibi in te, satis in legibus, satis in mediocribus amicitiis praesidii. Ergo ita: non posse honeste vivi, nisi honeste vivatur? Dolor ergo, id est summum malum, metuetur semper, etiamsi non aderit; Num igitur eum postea censes anxio animo aut sollicito fuisse? Nam et a te perfici istam disputationem volo, nec tua mihi oratio longa videri potest. Hoc positum in Phaedro a Platone probavit Epicurus sensitque in omni disputatione id fieri oportere.
            Summum a vobis bonum voluptas dicitur. Mihi, inquam, qui te id ipsum rogavi? Teneo, inquit, finem illi videri nihil dolere. Atqui haec patefactio quasi rerum opertarum, cum quid quidque sit aperitur, definitio est. Tanta vis admonitionis inest in locis; Videamus igitur sententias eorum, tum ad verba redeamus.
            Ego vero isti, inquam, permitto. Non semper, inquam; Multa sunt dicta ab antiquis de contemnendis ac despiciendis rebus humanis; Eam tum adesse, cum dolor omnis absit;
            Quid est, quod ab ea absolvi et perfici debeat? Et quod est munus, quod opus sapientiae? Gerendus est mos, modo recte sentiat. Sed tempus est, si videtur, et recta quidem ad me.
            Itaque hic ipse iam pridem est reiectus; At miser, si in flagitiosa et vitiosa vita afflueret voluptatibus. Pugnant Stoici cum Peripateticis. Utinam quidem dicerent alium alio beatiorem! Iam ruinas videres. Animum autem reliquis rebus ita perfecit, ut corpus; Prodest, inquit, mihi eo esse animo. Sin dicit obscurari quaedam nec apparere, quia valde parva sint, nos quoque concedimus;
            Quodsi vultum tibi, si incessum fingeres, quo gravior viderere, non esses tui similis; Nunc vero a primo quidem mirabiliter occulta natura est nec perspici nec cognosci potest. Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Primum Theophrasti, Strato, physicum se voluit; Quamquam haec quidem praeposita recte et reiecta dicere licebit.
            Ne in odium veniam, si amicum destitero tueri. Quis animo aequo videt eum, quem inpure ac flagitiose putet vivere? Equidem e Cn. Qui autem de summo bono dissentit de tota philosophiae ratione dissentit.
            Quod non faceret, si in voluptate summum bonum poneret. Hinc ceteri particulas arripere conati suam quisque videro voluit afferre sententiam. Quodsi vultum tibi, si incessum fingeres, quo gravior viderere, non esses tui similis; Paulum, cum regem Persem captum adduceret, eodem flumine invectio? Quibus ego vehementer assentior. Iam id ipsum absurdum, maximum malum neglegi. A mene tu? Ad quorum et cognitionem et usum iam corroborati natura ipsa praeeunte deducimur.
            Sed ne, dum huic obsequor, vobis molestus sim. At quicum ioca seria, ut dicitur, quicum arcana, quicum occulta omnia? Hoc tu nunc in illo probas. Quod quidem iam fit etiam in Academia. Ea, quae dialectici nunc tradunt et docent, nonne ab illis instituta sunt aut inventa sunt? Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. Nam prius a se poterit quisque discedere quam appetitum earum rerum, quae sibi conducant, amittere.
            Certe, nisi voluptatem tanti aestimaretis. Si stante, hoc natura videlicet vult, salvam esse se, quod concedimus; Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Non igitur potestis voluptate omnia dirigentes aut tueri aut retinere virtutem. Ergo ita: non posse honeste vivi, nisi honeste vivatur? Quamquam haec quidem praeposita recte et reiecta dicere licebit. Te ipsum, dignissimum maioribus tuis, voluptasne induxit, ut adolescentulus eriperes P. Atque ab his initiis profecti omnium virtutum et originem et progressionem persecuti sunt.
            Quod eo liquidius faciet, si perspexerit rerum inter eas verborumne sit controversia. Hoc loco tenere se Triarius non potuit. Quia nec honesto quic quam honestius nec turpi turpius. Ergo ita: non posse honeste vivi, nisi honeste vivatur? Et ille ridens: Video, inquit, quid agas; Tu quidem reddes; Qui autem de summo bono dissentit de tota philosophiae ratione dissentit. Atqui eorum nihil est eius generis, ut sit in fine atque extrerno bonorum. A primo, ut opinor, animantium ortu petitur origo summi boni.
            Esse enim, nisi eris, non potes. Egone non intellego, quid sit don Graece, Latine voluptas? Nec lapathi suavitatem acupenseri Galloni Laelius anteponebat, sed suavitatem ipsam neglegebat; Si enim ita est, vide ne facinus facias, cum mori suadeas. Earum etiam rerum, quas terra gignit, educatio quaedam et perfectio est non dissimilis animantium. Quodsi ipsam honestatem undique pertectam atque absolutam. Habent enim et bene longam et satis litigiosam disputationem. An potest, inquit ille, quicquam esse suavius quam nihil dolere?
            Qua tu etiam inprudens utebare non numquam. Non est enim vitium in oratione solum, sed etiam in moribus. In quibus doctissimi illi veteres inesse quiddam caeleste et divinum putaverunt. Indicant pueri, in quibus ut in speculis natura cernitur. Quod autem meum munus dicis non equidem recuso, sed te adiungo socium. In his igitur partibus duabus nihil erat, quod Zeno commutare gestiret.
            Atque haec coniunctio confusioque virtutum tamen a philosophis ratione quadam distinguitur. Quas enim kakaw Graeci appellant, vitia malo quam malitias nominare. Quid dubitas igitur mutare principia naturae? Quae hic rei publicae vulnera inponebat, eadem ille sanabat. Scio enim esse quosdam, qui quavis lingua philosophari possint; Itaque primos congressus copulationesque et consuetudinum instituendarum voluntates fieri propter voluptatem; Equidem, sed audistine modo de Carneade? Eodem modo is enim tibi nemo dabit, quod, expetendum sit, id esse laudabile. Virtutis, magnitudinis animi, patientiae, fortitudinis fomentis dolor mitigari solet. Quem Tiberina descensio festo illo die tanto gaudio affecit, quanto L.
            Nulla profecto est, quin suam vim retineat a primo ad extremum. In qua quid est boni praeter summam voluptatem, et eam sempiternam? Egone non intellego, quid sit don Graece, Latine voluptas? At ille pellit, qui permulcet sensum voluptate. Ac tamen hic mallet non dolere. Cetera illa adhibebat, quibus demptis negat se Epicurus intellegere quid sit bonum. Quae cum dixisset paulumque institisset, Quid est? Quis animo aequo videt eum, quem inpure ac flagitiose putet vivere? Sit enim idem caecus, debilis.
            Praeteritis, inquit, gaudeo. Duo Reges: constructio interrete. Quid ad utilitatem tantae pecuniae?
`;
